micronaut:
  application:
    name: marvel
  metrics:
    binders:
      jdbc:
        enabled: true
    enabled: true
  router:
    static-resources:
      swagger:
        paths:   classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths:   classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths:   classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths:   classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
#      default:
#        enabled: true
#        mapping: /**
#        paths:   classpath:META-INF/resources
#      webjars:
#        enabled: true
#        mapping: /webjars/**
#        paths:   classpath:META-INF/resources/webjars
#      swagger-ui:
#        paths:   classpath:META-INF/swagger/views/swagger-ui
#        mapping: /swagger-ui/**
  server:
    cors:
      enabled: true
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
jackson:
  bean-introspection-module: true
jpa:
  default:
#spring.jpa:
#    packages-to-scan:
#      - 'example.micronaut.domain'
    open-in-view: false
    properties:
        bytecode.use_reflection_optimizer:          true
#        cache.use_query_cache:                      true
        cache.use_second_level_cache:               false
        connection.characterEncoding:               utf8
        connection.CharSet:                         utf8
        connection.generateSimpleParameterMetadata: true
        connection.isolation:                       2
        connection.pool_size:                       33
        connection.profileSQL:                      true
        connection.handling_mode:                   DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
        connection.rewriteBatchedStatements:        true
        connection.useBatchMultiSend:               true
        connection.useUnicode:                      true
        current_session_context_class:              org.springframework.orm.hibernate5.SpringSessionContext
        enhancer.enableLazyInitialization:          true
        event.merge.entity_copy_observer:           log
        format_sql:                                 true
        generate_statistics:                        true
        hbm2ddl.auto:                               update
        implicit_naming_strategy:                   com.example.marvel.convention.jpa.naming.ImplicitNamingStrategyImpl
        jdbc.batch_size:                            33
        jdbc.fetch_size:                            200
        jdbc.use_streams_for_binary:                true
        max_fetch_depth:                            5
        physical_naming_strategy:                   com.example.marvel.convention.jpa.naming.PhysicalNamingStrategyImpl
        query.in_clause_parameter_padding:          true
        query.plan_parameter_metadata_max_size:     2048
        query.substitutions:                        true 1, false 0, yes 'Y', no 'N'
        show_sql:                                   false
        statement_cache.size:                       100
        use_sql_comments:                           true
endpoints:
  all:
    port: 8085
    enabled:   true
    sensitive: false

