micronaut:
  application:
    name: marvel
  router:
    static-resources:
      swagger:
        paths:   classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths:   classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths:   classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths:   classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
#      default:
#        enabled: true
#        mapping: /**
#        paths:   classpath:META-INF/resources
#      webjars:
#        enabled: true
#        mapping: /webjars/**
#        paths:   classpath:META-INF/resources/webjars
#      swagger-ui:
#        paths:   classpath:META-INF/swagger/views/swagger-ui
#        mapping: /swagger-ui/**
  server:
    cors:
      enabled: true
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
jackson:
  bean-introspection-module: true
jpa:
  default:
#    packages-to-scan:
#      - 'example.micronaut.domain'
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        implicit_naming_strategy: com.example.marvel.convention.jpa.naming.ImplicitNamingStrategyImpl
        physical_naming_strategy: com.example.marvel.convention.jpa.naming.PhysicalNamingStrategyImpl
        show_sql: true
spring:
  jpa:
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
