{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-io/0.3.0/kotlinx-io-0.3.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-io",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "yirq6rgvjnce5eph7jw74umnca"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-io-jvm-0.3.0.jar",
          "url": "kotlinx-io-jvm-0.3.0.jar",
          "size": 118589,
          "sha512": "0758e910b57997c3bc4a4214cb0e3af6687b6d2c914aecdc66facb7eaf2c2b2436a41c40e640613d6e4246d592db4a848b03069a9399047e6faade4d72180404",
          "sha256": "56d604e6f901dad8b2d92d1f33f8fce8091b14f928c51739f2a6c0f50cf0dd6e",
          "sha1": "0626de70f5c48dd994a3ca219b4a53ea08521f4a",
          "md5": "3d71cf87d4a6564f42f21ae47523bca9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-io-jvm-0.3.0.jar",
          "url": "kotlinx-io-jvm-0.3.0.jar",
          "size": 118589,
          "sha512": "0758e910b57997c3bc4a4214cb0e3af6687b6d2c914aecdc66facb7eaf2c2b2436a41c40e640613d6e4246d592db4a848b03069a9399047e6faade4d72180404",
          "sha256": "56d604e6f901dad8b2d92d1f33f8fce8091b14f928c51739f2a6c0f50cf0dd6e",
          "sha1": "0626de70f5c48dd994a3ca219b4a53ea08521f4a",
          "md5": "3d71cf87d4a6564f42f21ae47523bca9"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlinx-io-metadata/0.3.0/kotlinx-io-metadata-0.3.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-metadata",
        "version": "0.3.0"
      }
    }
  ]
}
