{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kotlinx-io/0.2.0/kotlinx-io-0.2.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-io",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.6.2",
      "buildId": "nozualtohneidbdrl6lbicjuxe"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-io-jvm-0.2.0.jar",
          "url": "kotlinx-io-jvm-0.2.0.jar",
          "size": 118701,
          "sha1": "12c0ccf48bc8807562992c4e4893f84473678c9c",
          "md5": "ac94d0617df35cc2cd5780566af23aff"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-io-jvm-0.2.0.jar",
          "url": "kotlinx-io-jvm-0.2.0.jar",
          "size": 118701,
          "sha1": "12c0ccf48bc8807562992c4e4893f84473678c9c",
          "md5": "ac94d0617df35cc2cd5780566af23aff"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlinx-io-metadata/0.2.0/kotlinx-io-metadata-0.2.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-metadata",
        "version": "0.2.0"
      }
    }
  ]
}
